name: 'Base Linux Action'
description: 'An example action to use in GitHub workflows'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      run: git checkout ${{ github.sha }}
      shell: bash

    # - name: Set up Node.js
    #   run: |
    #     curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    #     sudo apt-get install -y nodejs
    #   shell: bash

    - name: Debug
      run: echo "$HOUSE"
      shell: bash
