name: 'Repo1 Action'
description: 'Composite action for Repo1'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      run: git checkout ${{ github.sha }}
      shell: bash

    - name: Set up Node.js
      run: |
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
      shell: bash

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash
