name: 'Base Linux Action'
description: 'An example action to use in GitHub workflows'
runs:
  using: 'composite'
  steps:
    - name: Parse secrets
      run: |
      echo "$SECRETS_JSON" > secrets.json
      jq -r 'to_entries | .[] | "export \(.key|ascii_upcase)=\(.value)"' secrets.json > set_env_vars.sh
      source set_env_vars.sh
      # Save environment variables for the next steps
      echo "source $PWD/set_env_vars.sh" >> $GITHUB_ENV
    shell: bash
    
    - name: Checkout code
      run: git checkout ${{ github.sha }}
      shell: bash

    # - name: Set up Node.js
    #   run: |
    #     curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    #     sudo apt-get install -y nodejs
    #   shell: bash

    - name: Debug
      run: |
        echo "HOUSE: $HOUSE"
      shell: bash
