name: 'Repo1 Action'
description: 'Composite action for Repo1'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      run: git checkout ${{ github.sha }}

    - name: Set up Node.js
      run: |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
