# Called workflow (reusable.yml)
name: Reusable workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - run: echo "Hello ${{ inputs.username }}"